export const GET_POSTS = 'GET_POSTS'
export const POST_POST = 'POST_POST'
export const DEL_POST = 'DEL_POST'

export const GET_USER = 'GET_USER'
export const GET_USER_POSTS = 'GET_USER_POSTS'
export const GET_USER_INFOS = 'GET_USER_INFOS'
export const DEL_USER_INFOS = 'DEL_USER_INFOS'

export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_IS_LOGGED_IN = 'USER_IS_LOGGED_IN'

export const EDITOR_SAVE = 'EDITOR_SAVE'
export const EDITOR_CLEAN = 'EDITOR_CLEAN'

export const GEOGRAPHY_SETUP = 'GEOGRAPHY_SETUP'
export const GEO_INCREMENT_COUNTER = 'GEO_INCREMENT_COUNTER'
export const GEO_INCREMENT_SCORE = 'GEO_INCREMENT_SCORE'
export const GEO_ADD_ANSWER = 'GEO_ADD_ANSWER'
export const GEO_SET_TYPE = 'GEO_SET_TYPE'
